### ISSUE TITLE
Still problems with ADF

### ISSUE THREAD

**Issue by ChrisPUA320** [nguyenquyhy/Flight-Tracker-StreamDeck#359]
After the udate 0.45 there are still problems with ADF not working properly.
 -ADF 2 only swaps ADF 1 and not ADF 2
- entering frequencies for ADF 1+2 via the numpad is not working

Please check on this issue.

Thanks and rgds
Chris PU // A320

**Comment by nguyenquyhy** [comment]
> After the udate 0.45 there are still problems with ADF not working properly. -ADF 2 only swaps ADF 1 and not ADF 2

Yup I noticed this too. However, ADF2 button already sends the correct event `ADF2_RADIO_SWAP`. 
The good news is that I am on Sim Update 11 beta and I don't see this issue anymore. I think Asobo has fixed it.

> * entering frequencies for ADF 1+2 via the numpad is not working

Can you be more specific here? I have not seen this issue before.
Do you see the numpad? Which aircraft and which frequency has you been trying with? Maybe a video capture would help me to understand the issue here.

**Comment by ChrisPUA320** [comment]
The numpad opens with ADF 1 and 2. But only ADF 1 accepts the entries in the numpad. Doesn’t matter which frequencies. Happens with all aircraft. Both ADFs show the correct frequencies when entering in the aircraft itself but that doesn’t happen with ADF2 when trying to enter via the numpad.RgdsChris Von meinem iPhone gesendetAm 16.10.2022 um 00:58 schrieb Nguyễn Quý Hy ***@***.***>:﻿

After the udate 0.45 there are still problems with ADF not working properly. -ADF 2 only swaps ADF 1 and not ADF 2

Yup I noticed this too. However, ADF2 button already sends the correct event ADF2_RADIO_SWAP.
The good news is that I am on Sim Update 11 beta and I don't see this issue anymore. I think Asobo has fixed it.


entering frequencies for ADF 1+2 via the numpad is not working


Can you be more specific here? I have not seen this issue before.
Do you see the numpad? Which aircraft and which frequency has you been trying with? Maybe a video capture would help me to understand the issue here.

**Comment by nguyenquyhy** [comment]
I'm confused here, so can you enter the frequency for ADF1?

If the issue is only on ADF2, I think it is MSFS issue and looks like it is already fixed in SU11.

**Comment by ChrisPUA320** [comment]
Both ADFs (1 and 2) are able to open the numpad. You can enter frequencies, but when hitting “enter” NONE of them will show the freqs in the window when it reverts back out of the numpad. It just doesn’t get saved somehow. When you enter the frequencies within the aircraft panel itself, then the frequencies are shown accordingly to ADF 1 and 2. Just doesn’t work with the numpad.

 �

Rgds

 �

Chris

 �

**Comment by nguyenquyhy** [comment]
Are you testing with the default 172? I remember entering ADF frequency was fine when I was testing in SU10. It is still working properly in SU11 beta.

Can you please try to enter again, then provide me the logs file in `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin`? Those with name similar to flightstreamdeck20221016.log. Please also let me know the frequency you have entered.

**Comment by ChrisPUA320** [comment]
Hi Nguyen,

  

anything new on the ADF issue yet?

  

Regards

  

Chris

  

From: Chris Gerstel ***@***.*** 
Sent: Monday, October 17, 2022 1:10 PM
To: 'Chris Gerstel' ***@***.***>
Subject: RE: [nguyenquyhy/Flight-Tracker-StreamDeck] Still problems with ADF (Issue #359)

 �

I was testing this with the C-172. Entering the frequencies via numpad is not possible for BOTH ADFs although the numpad opens and it shows which ADF is chosen (1 or 2). When entering the frequency inside the cockpit it enters it in ADF2 instead of ADF1 (there is only ADF1 in a Cessna 172). When trying to swap the frequencies it swaps between ADF 1 and 2 and NOT only ADF1. I have enclosed a short video showing the issue and also enclosed the logfile.

Regards

Chris

 �

 �

Von: Nguyễn Quý Hy ***@***.*** ***@***.***> >
Datum: 16. Oktober 2022 um 21:49:58 MESZ
An: nguyenquyhy/Flight-Tracker-StreamDeck ***@***.*** ***@***.***> >
Kopie: ChrisPUA320 ***@***.*** ***@***.***> >, Author ***@***.*** ***@***.***> >
Betreff: Aw: [nguyenquyhy/Flight-Tracker-StreamDeck] Still problems with ADF (Issue #359)
Antwort an: nguyenquyhy/Flight-Tracker-StreamDeck ***@***.*** ***@***.***> >

﻿

Are you testing with the default 172? I remember entering ADF frequency was fine when I was testing in SU10. It is still working properly in SU11 beta.

Can you please try to enter again, then provide me the logs file in %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin? Those with name similar to flightstreamdeck20221016.log. Please also let me know the frequency you have entered.

**Comment by nguyenquyhy** [comment]
Are you able to give me the logs?

As I mentioned I don't see any issue on Sim Update 11, maybe that should fix the issue you are having.

**Comment by ChrisPUA320** [comment]
I sent you logs with my last mail (also a video of this issue). I have enclosed the log again. I don’t think that all issues (because there are more with the ADF) are FS related. As I mentioned in my last mail it is NOT possible to enter freqs for ADF via the numpad etc. I have enclosed my last mail down below just in case it got lost somewhere…

 �

I was testing this with the C-172. Entering the frequencies via numpad is not possible for BOTH ADFs although the numpad opens and it shows which ADF is chosen (1 or 2). When entering the frequency inside the cockpit it enters it in ADF2 instead of ADF1 (there is only ADF1 in a Cessna 172). When trying to swap the frequencies it swaps between ADF 1 and 2 and NOT only ADF1. I have enclosed a short video showing the issue and also enclosed the logfile.

Regards

Chris

 �

 �

**Comment by nguyenquyhy** [comment]
I don't think you can send log with email attachments. Can you please do to GitHub directly?

For the first issue with entering numbers, a video would help me to understand what you are getting.

For the issue of swapping ADF2, as I have mentioned, that is already fixed in Sim Update 11. You can either wait for the update next weekend, or try the public beta.

**Comment by ChrisPUA320** [comment]
Hi Nguyen,

 �

now I have installed the published SU11. Swapping of ADF1 and 2 is working so far. But the issue with entering ADF frequencies via the numpad still persists. It is NOT possible to enter frequencies for ADF1/2 with the numpad as shown in the video I have enclosed. Also the Standby frequency is NOT shown correctly as you can see in the video. When you enter the standby frequency in the aircraft and swap it as active then it is shown correctly. Please see for yourself…

 �

regards

 �

Chris

 �

**Comment by nguyenquyhy** [comment]
Can you please go to GitHub and attach the video? I cannot see your email attachment.

**Comment by ChrisPUA320** [comment]
Here is the video...

https://user-images.githubusercontent.com/113291887/201489868-f7e81da6-30a2-40a9-ac5f-1e207bb27789.mp4

**Comment by nguyenquyhy** [comment]
Thanks for the video. Let me check that out.

**Comment by nguyenquyhy** [comment]
I found the issue and will release a new version today. However, it still won't work on a few aircraft such as the A310 because the aircraft will keep overriding the value for its special switching behavior.

**Comment by nguyenquyhy** [comment]
I have released version 0.46 on GitHub with a fix for this. Please try again and let me know if it works for you.

**Comment by ChrisPUA320** [comment]
Thank you Regard’s Chris Von meinem iPhone gesendetAm 13.11.2022 um 19:59 schrieb Nguyễn Quý Hy ***@***.***>:﻿
I found the issue and will release a new version today. However, it still won't work on a few aircraft such as the A310 because the aircraft will keep overriding the value for its special switching behavior.

**Comment by ChrisPUA320** [comment]
Hi,

 �

unfortunately it still doesn’t work. I tried it with the A310…but no matter what aircraft I use, entering the frequency via the integrated numpad is still not possible. If I change the freqs in the aircraft it shows the correct values but not if it is entered via the numpad. I guess you have to look into that again. And it is not only at my PC, all the people I talked to have the same problem with the ADF. Even after the version 0.46. I am a developer of Streamdeck profiles and AAO scripts etc. so everyone I have talked to told me the same thing….

 �

Regards

 �

Chris

 �

**Comment by nguyenquyhy** [comment]
This is strange. Can you please try on the C172?

It works fine for me.
https://jmp.sh/BWSCZDUv

**Comment by ChrisPUA320** [comment]
Seems to work now. But still having troubles in e.g. A310. No entering of the ADF frequencies via numpad possible…it works in C-172 or the PMDG737

 �

Regards

Chris

 �
